import "./globals.css";
import { libreFranklin } from "./fonts";
import Navbar from "@/components/nav-bar";
import BottomPanel from "@/components/bottom-panel";
// import { Analytics } from '@vercel/analytics/react';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${libreFranklin.className} background text-white box-border h-screen w-screen max-h-screen max-w-screen`}
    >
      <body className="antialiased w-screen h-full sm:h-screen max-h-screen max-w-screen flex flex-col items-center">
        <main className="flex-auto min-w-0 mt-6 flex flex-col w-full sm:w-[525px] relative px-6 sm:px-0">
          <Navbar />
          {children}
          {/* <Analytics /> */}
          <BottomPanel />
        </main>
      </body>
    </html>
  );
}
